### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by leondz** [lfwa/carbontracker#24]
Could it be a long-term goal to support Intel RAPL on OSX?

```
leod@mac610965:~/dev/lowtest$ python3 ct.py
CarbonTracker: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/carbontracker/tracker.py", line 100, in run
    self.begin()
  File "/usr/local/lib/python3.7/site-packages/carbontracker/tracker.py", line 114, in begin
    self._components_remove_unavailable()
  File "/usr/local/lib/python3.7/site-packages/carbontracker/tracker.py", line 167, in _components_remove_unavailable
    raise exceptions.NoComponentsAvailableError()
carbontracker.exceptions.NoComponentsAvailableError: No components were available. CarbonTracker supports Intel CPUs with the RAPL interface and NVIDIA GPUs.
```

**Comment by kanding** [comment]
For sure!

We'd like to support as much as possible. If I remember correctly then reading energy measurements on Mac OS was difficult without user access restrictions, which we really wanted to avoid with _carbontracker_

**Comment by AndyNano** [comment]
I get the same error when running on Nvidia GPU. Have you seen this before?



Traceback (most recent call last):
  File "/home/nanostructure/anaconda3/lib/python3.7/site-packages/carbontracker/tracker.py", line 100, in run
    self.begin()
  File "/home/nanostructure/anaconda3/lib/python3.7/site-packages/carbontracker/tracker.py", line 114, in begin
    self._components_remove_unavailable()
  File "/home/nanostructure/anaconda3/lib/python3.7/site-packages/carbontracker/tracker.py", line 167, in _components_remove_unavailable
    raise exceptions.NoComponentsAvailableError()
carbontracker.exceptions.NoComponentsAvailableError: No components were available. CarbonTracker supports Intel CPUs with the RAPL interface and NVIDIA GPUs.

CarbonTracker: Traceback (most recent call last):
  File "/home/nanostructure/anaconda3/lib/python3.7/site-packages/carbontracker/tracker.py", line 100, in run
    self.begin()
  File "/home/nanostructure/anaconda3/lib/python3.7/site-packages/carbontracker/tracker.py", line 114, in begin
    self._components_remove_unavailable()
  File "/home/nanostructure/anaconda3/lib/python3.7/site-packages/carbontracker/tracker.py", line 167, in _components_remove_unavailable
    raise exceptions.NoComponentsAvailableError()
carbontracker.exceptions.NoComponentsAvailableError: No components were available. CarbonTracker supports Intel CPUs with the RAPL interface and NVIDIA GPUs.

**Comment by lfwa** [comment]
Hi Andy,

What setup are you running on?

For NVIDIA GPUs we rely on the NVIDIA Management Library (NVML through pynvml) to query the GPU state. I have not yet tested if this or nvidia-smi is available on macOS.
