### ISSUE TITLE
CarbonTracker: CRITICAL

### ISSUE THREAD

**Issue by tuanaqeelbohoran** [lfwa/carbontracker#57]
CarbonTracker: CRITICAL - Traceback (most recent call last):
  File "C:\Users\PHY3BOHORT\Anaconda3\Lib\site-packages\carbontracker\tracker.py", line 117, in run
    self.begin()
  File "C:\Users\PHY3BOHORT\Anaconda3\Lib\site-packages\carbontracker\tracker.py", line 131, in begin
    self._components_remove_unavailable()
  File "C:\Users\PHY3BOHORT\Anaconda3\Lib\site-packages\carbontracker\tracker.py", line 187, in _components_remove_unavailable
    raise exceptions.NoComponentsAvailableError()
carbontracker.exceptions.NoComponentsAvailableError: No components were available. CarbonTracker supports Intel CPUs with the RAPL interface and NVIDIA GPUs.

CarbonTracker: Traceback (most recent call last):
  File "C:\Users\PHY3BOHORT\Anaconda3\Lib\site-packages\carbontracker\tracker.py", line 117, in run
    self.begin()
  File "C:\Users\PHY3BOHORT\Anaconda3\Lib\site-packages\carbontracker\tracker.py", line 131, in begin
    self._components_remove_unavailable()
  File "C:\Users\PHY3BOHORT\Anaconda3\Lib\site-packages\carbontracker\tracker.py", line 187, in _components_remove_unavailable
    raise exceptions.NoComponentsAvailableError()
carbontracker.exceptions.NoComponentsAvailableError: No components were available. CarbonTracker supports Intel CPUs with the RAPL interface and NVIDIA GPUs.

**Comment by PedramBakh** [comment]
Your issue appears to be somewhat similar to Issue #55. This could potentially be due to compatibility challenges with certain Intel CPUs or NVIDIA GPUs on specific platforms. Please note that in our latest [Release v1.2.0](https://github.com/lfwa/carbontracker/releases/tag/v1.2.0), we've enhanced support to include OSX (M1/M2) chips. If you believe there are distinct aspects not covered in Issue #55 or have further specifics to share, please feel free to open a new issue, and we'll be more than happy to investigate further.
